### ISSUE TITLE
What's the difference between this plugin and the already available "Random points on lines" and "Random points along line" processing algorithms?

### ISSUE THREAD

**Issue by agiudiceandrea** [gisinnovationmy/RandomPointsonLines#1]

**Comment by MyGIS** [comment]
We need to have quick access to it for our project and this plug-in ads additional attributes to the point adding the distance from the start of the line.

**Comment by agiudiceandrea** [comment]
Thanks. It would be useful to add such info in the plugin's description.

**Comment by MyGIS** [comment]
You are right Andrea. We will add that in the next update, most probably by this week as there is a lot to be added into it. Your feedback is always welcome !

**Comment by gisinnovationmy** [comment]
Hello @agiudiceandrea,

Thank you for taking the time to raise this issue and for your valuable feedback. If there’s anything else you’d like to suggest or inquire about, please don’t hesitate to open another issue or reach out.

Thanks again for your support!

**Comment by gisinnovationmy** [comment]
Hello @agiudiceandrea,

Thank you for taking the time to raise this issue and for your valuable feedback. If there’s anything else you’d like to suggest or inquire about, please don’t hesitate to open another issue or reach out.

Thanks again for your support!
